version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: governance-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: governance_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./DB_schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - governance-network

  # Backend API
  backend:
    build: .
    container_name: governance-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
                  - MONGODB_URI=mongodb://admin:password123@mongodb:27017/?retryWrites=true&w=majority&appName=Governance-AI&authSource=admin
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - governance-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  governance-network:
    driver: bridge 